# Project: atty
# Makefile created by Steve Chang
# Date modified: 2024.11.30

LIBNAME = libserial.a

DIR = serial

SUBDIR =

INCLUDE =

SRCS = $(wildcard *.c)

OBJDIR = obj

ASMDIR = asm

include $(MAKE_RULES)
