# Project: algo4linux
# Makefile created by Steve Chang
# Date modified: 2024.06.22

LIBNAME = libmain.a

DIR = src

SUBDIR =

INCLUDE =

SRCS = $(wildcard *.c)

OBJDIR = obj

ASMDIR = asm

include $(MAKE_RULES)
